name: Destroy-AKS-Resources

on:
  workflow_dispatch:

jobs:
  destroy-aks-resources:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: medrh11
      IMAGE_NAME: web-app
      AKS_RESOURCE_GROUP: rg-aks-cluster-tf-023
      AKS_NAME: aks-cluster
      ACR_NAME: acrforakstf023
      TERRAFORM_VERSION: 1.4.6
      WORKING_DIRECTORY: infra
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
    steps:
    - uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        
    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run:
        terraform init

    - name: Terraform Destroy
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform destroy -auto-approve
